// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/diffservice.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CalcImageDiffsRequest struct {
	Image1               *Image   `protobuf:"bytes,1,opt,name=image1,proto3" json:"image1,omitempty"`
	Image2               *Image   `protobuf:"bytes,2,opt,name=image2,proto3" json:"image2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalcImageDiffsRequest) Reset()         { *m = CalcImageDiffsRequest{} }
func (m *CalcImageDiffsRequest) String() string { return proto.CompactTextString(m) }
func (*CalcImageDiffsRequest) ProtoMessage()    {}
func (*CalcImageDiffsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cc1287a3435a7b8, []int{0}
}

func (m *CalcImageDiffsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalcImageDiffsRequest.Unmarshal(m, b)
}
func (m *CalcImageDiffsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalcImageDiffsRequest.Marshal(b, m, deterministic)
}
func (m *CalcImageDiffsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalcImageDiffsRequest.Merge(m, src)
}
func (m *CalcImageDiffsRequest) XXX_Size() int {
	return xxx_messageInfo_CalcImageDiffsRequest.Size(m)
}
func (m *CalcImageDiffsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalcImageDiffsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalcImageDiffsRequest proto.InternalMessageInfo

func (m *CalcImageDiffsRequest) GetImage1() *Image {
	if m != nil {
		return m.Image1
	}
	return nil
}

func (m *CalcImageDiffsRequest) GetImage2() *Image {
	if m != nil {
		return m.Image2
	}
	return nil
}

type CalculateDeltaDiffsResponse struct {
	DeltaDiff            []byte   `protobuf:"bytes,1,opt,name=delta_diff,json=deltaDiff,proto3" json:"delta_diff,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculateDeltaDiffsResponse) Reset()         { *m = CalculateDeltaDiffsResponse{} }
func (m *CalculateDeltaDiffsResponse) String() string { return proto.CompactTextString(m) }
func (*CalculateDeltaDiffsResponse) ProtoMessage()    {}
func (*CalculateDeltaDiffsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cc1287a3435a7b8, []int{1}
}

func (m *CalculateDeltaDiffsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculateDeltaDiffsResponse.Unmarshal(m, b)
}
func (m *CalculateDeltaDiffsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculateDeltaDiffsResponse.Marshal(b, m, deterministic)
}
func (m *CalculateDeltaDiffsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculateDeltaDiffsResponse.Merge(m, src)
}
func (m *CalculateDeltaDiffsResponse) XXX_Size() int {
	return xxx_messageInfo_CalculateDeltaDiffsResponse.Size(m)
}
func (m *CalculateDeltaDiffsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculateDeltaDiffsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalculateDeltaDiffsResponse proto.InternalMessageInfo

func (m *CalculateDeltaDiffsResponse) GetDeltaDiff() []byte {
	if m != nil {
		return m.DeltaDiff
	}
	return nil
}

type ManifestRequest struct {
	Image                *Image   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Os                   string   `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch                 string   `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManifestRequest) Reset()         { *m = ManifestRequest{} }
func (m *ManifestRequest) String() string { return proto.CompactTextString(m) }
func (*ManifestRequest) ProtoMessage()    {}
func (*ManifestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cc1287a3435a7b8, []int{2}
}

func (m *ManifestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManifestRequest.Unmarshal(m, b)
}
func (m *ManifestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManifestRequest.Marshal(b, m, deterministic)
}
func (m *ManifestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManifestRequest.Merge(m, src)
}
func (m *ManifestRequest) XXX_Size() int {
	return xxx_messageInfo_ManifestRequest.Size(m)
}
func (m *ManifestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ManifestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ManifestRequest proto.InternalMessageInfo

func (m *ManifestRequest) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *ManifestRequest) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *ManifestRequest) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

type ManifestResponse struct {
	Manifest             []byte   `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	ImageConfig          []byte   `protobuf:"bytes,2,opt,name=imageConfig,proto3" json:"imageConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManifestResponse) Reset()         { *m = ManifestResponse{} }
func (m *ManifestResponse) String() string { return proto.CompactTextString(m) }
func (*ManifestResponse) ProtoMessage()    {}
func (*ManifestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cc1287a3435a7b8, []int{3}
}

func (m *ManifestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManifestResponse.Unmarshal(m, b)
}
func (m *ManifestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManifestResponse.Marshal(b, m, deterministic)
}
func (m *ManifestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManifestResponse.Merge(m, src)
}
func (m *ManifestResponse) XXX_Size() int {
	return xxx_messageInfo_ManifestResponse.Size(m)
}
func (m *ManifestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ManifestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ManifestResponse proto.InternalMessageInfo

func (m *ManifestResponse) GetManifest() []byte {
	if m != nil {
		return m.Manifest
	}
	return nil
}

func (m *ManifestResponse) GetImageConfig() []byte {
	if m != nil {
		return m.ImageConfig
	}
	return nil
}

type Image struct {
	Reference            string   `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cc1287a3435a7b8, []int{4}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func init() {
	proto.RegisterType((*CalcImageDiffsRequest)(nil), "deltadiff.CalcImageDiffsRequest")
	proto.RegisterType((*CalculateDeltaDiffsResponse)(nil), "deltadiff.CalculateDeltaDiffsResponse")
	proto.RegisterType((*ManifestRequest)(nil), "deltadiff.ManifestRequest")
	proto.RegisterType((*ManifestResponse)(nil), "deltadiff.ManifestResponse")
	proto.RegisterType((*Image)(nil), "deltadiff.Image")
}

func init() {
	proto.RegisterFile("api/diffservice.proto", fileDescriptor_9cc1287a3435a7b8)
}

var fileDescriptor_9cc1287a3435a7b8 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x49, 0xb5, 0xd5, 0x4c, 0x8b, 0x96, 0x91, 0x42, 0x49, 0x15, 0x4a, 0xc0, 0xd2, 0x53,
	0xaa, 0xf1, 0xea, 0xc9, 0x16, 0xc5, 0x83, 0x20, 0xeb, 0x4d, 0x10, 0x59, 0xd3, 0x49, 0x5d, 0x6c,
	0xb3, 0x31, 0xbb, 0xf5, 0xdf, 0xf9, 0xdf, 0x64, 0x37, 0x69, 0x1a, 0x4a, 0xea, 0x2d, 0x79, 0xf3,
	0xe6, 0xcd, 0xb7, 0xb3, 0x0b, 0x3d, 0x9e, 0x8a, 0xc9, 0x5c, 0xc4, 0xb1, 0xa2, 0xec, 0x47, 0x44,
	0x14, 0xa4, 0x99, 0xd4, 0x12, 0xdd, 0x39, 0x2d, 0x35, 0x37, 0xba, 0xff, 0x05, 0xbd, 0x29, 0x5f,
	0x46, 0x8f, 0x2b, 0xbe, 0xa0, 0x99, 0x31, 0x32, 0xfa, 0x5e, 0x93, 0xd2, 0x38, 0x86, 0x96, 0x30,
	0xe2, 0x75, 0xdf, 0x19, 0x3a, 0xe3, 0x76, 0xd8, 0x0d, 0xca, 0xa6, 0xc0, 0xba, 0x59, 0x51, 0x2f,
	0x9d, 0x61, 0xbf, 0xf1, 0xaf, 0x33, 0xf4, 0x6f, 0x61, 0x60, 0x86, 0xad, 0x97, 0x5c, 0xd3, 0xcc,
	0x78, 0x8a, 0x89, 0x2a, 0x95, 0x89, 0x22, 0xbc, 0x00, 0xb0, 0x9d, 0xef, 0xa6, 0xd5, 0x8e, 0xed,
	0xb0, 0x1c, 0xd5, 0xf8, 0xfc, 0x37, 0x38, 0x7d, 0xe2, 0x89, 0x88, 0x49, 0xe9, 0x0d, 0xe4, 0x08,
	0x9a, 0x36, 0x7a, 0x2f, 0x63, 0x5e, 0xc6, 0x13, 0x68, 0x48, 0x65, 0xf1, 0x5c, 0xd6, 0x90, 0x0a,
	0x11, 0x0e, 0x79, 0x16, 0x7d, 0xf6, 0x0f, 0xac, 0x62, 0xbf, 0xfd, 0x67, 0xe8, 0x6e, 0xe3, 0x0b,
	0x22, 0x0f, 0x8e, 0x57, 0x85, 0x56, 0xf0, 0x94, 0xff, 0x38, 0x84, 0xb6, 0x0d, 0x9f, 0xca, 0x24,
	0x16, 0x0b, 0x1b, 0xde, 0x61, 0x55, 0xc9, 0xbf, 0x84, 0xa6, 0xa5, 0xc0, 0x73, 0x70, 0x33, 0x8a,
	0x29, 0xa3, 0x24, 0xca, 0x51, 0x5d, 0xb6, 0x15, 0xc2, 0x5f, 0x07, 0xba, 0xe5, 0x36, 0x5e, 0xf2,
	0x8b, 0x42, 0x0e, 0x67, 0x35, 0xab, 0xc2, 0x61, 0xe5, 0x84, 0xb5, 0xf7, 0xe6, 0x8d, 0x76, 0x1c,
	0x7b, 0x96, 0x7d, 0xe5, 0xe0, 0x3d, 0xb4, 0x1f, 0x48, 0x6f, 0xce, 0x8c, 0x5e, 0xa5, 0x71, 0x67,
	0xcf, 0xde, 0xa0, 0xb6, 0x96, 0x27, 0xdd, 0x1d, 0xbd, 0x36, 0x83, 0x09, 0x4f, 0xc5, 0x47, 0xcb,
	0xbe, 0xae, 0x9b, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x22, 0x72, 0xf8, 0x76, 0x02, 0x00,
	0x00,
}
